# Generated by Django 2.1.1 on 2019-08-13 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0003_auto_20190806_0452'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name_plural': 'Posts'},
        ),
    ]
