# Generated by Django 2.1.1 on 2019-08-13 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0005_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
